/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace DeletionProver {
  export type DeletionRecordStruct = {
    vaultId: BytesLike;
    tombstoneHash: BytesLike;
    deletedHashes: BytesLike[];
    operator: AddressLike;
    deletedAt: BigNumberish;
    gdprBasis: string;
    userIdentifier: string;
    blockNumber: BigNumberish;
  };

  export type DeletionRecordStructOutput = [
    vaultId: string,
    tombstoneHash: string,
    deletedHashes: string[],
    operator: string,
    deletedAt: bigint,
    gdprBasis: string,
    userIdentifier: string,
    blockNumber: bigint
  ] & {
    vaultId: string;
    tombstoneHash: string;
    deletedHashes: string[];
    operator: string;
    deletedAt: bigint;
    gdprBasis: string;
    userIdentifier: string;
    blockNumber: bigint;
  };
}

export interface DeletionProverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deletedHashes"
      | "deletionCounter"
      | "deletions"
      | "getDeletion"
      | "getVaultDeletions"
      | "isDeleted"
      | "owner"
      | "proveDeletion"
      | "registerVaultOperator"
      | "renounceOwnership"
      | "transferOwnership"
      | "vaultDeletions"
      | "vaultOperators"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeletionProved"
      | "OwnershipTransferred"
      | "VaultOperatorRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deletedHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deletionCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deletions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeletion",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultDeletions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDeleted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proveDeletion",
    values: [BytesLike, BytesLike[], string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerVaultOperator",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultDeletions",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultOperators",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "deletedHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deletionCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deletions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDeletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultDeletions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isDeleted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proveDeletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerVaultOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultDeletions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultOperators",
    data: BytesLike
  ): Result;
}

export namespace DeletionProvedEvent {
  export type InputTuple = [
    deletionId: BigNumberish,
    vaultId: BytesLike,
    tombstoneHash: BytesLike,
    operator: AddressLike,
    deletedAt: BigNumberish,
    gdprBasis: string
  ];
  export type OutputTuple = [
    deletionId: bigint,
    vaultId: string,
    tombstoneHash: string,
    operator: string,
    deletedAt: bigint,
    gdprBasis: string
  ];
  export interface OutputObject {
    deletionId: bigint;
    vaultId: string;
    tombstoneHash: string;
    operator: string;
    deletedAt: bigint;
    gdprBasis: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultOperatorRegisteredEvent {
  export type InputTuple = [vaultId: BytesLike, operator: AddressLike];
  export type OutputTuple = [vaultId: string, operator: string];
  export interface OutputObject {
    vaultId: string;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DeletionProver extends BaseContract {
  connect(runner?: ContractRunner | null): DeletionProver;
  waitForDeployment(): Promise<this>;

  interface: DeletionProverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deletedHashes: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  deletionCounter: TypedContractMethod<[], [bigint], "view">;

  deletions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, string, string, bigint] & {
        vaultId: string;
        tombstoneHash: string;
        operator: string;
        deletedAt: bigint;
        gdprBasis: string;
        userIdentifier: string;
        blockNumber: bigint;
      }
    ],
    "view"
  >;

  getDeletion: TypedContractMethod<
    [deletionId: BigNumberish],
    [DeletionProver.DeletionRecordStructOutput],
    "view"
  >;

  getVaultDeletions: TypedContractMethod<
    [vaultId: BytesLike],
    [bigint[]],
    "view"
  >;

  isDeleted: TypedContractMethod<[contentHash: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  proveDeletion: TypedContractMethod<
    [
      vaultId: BytesLike,
      deletedContentHashes: BytesLike[],
      gdprBasis: string,
      userIdentifier: string,
      operatorSig: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  registerVaultOperator: TypedContractMethod<
    [vaultId: BytesLike, operator: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vaultDeletions: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  vaultOperators: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deletedHashes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deletionCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deletions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, string, string, bigint] & {
        vaultId: string;
        tombstoneHash: string;
        operator: string;
        deletedAt: bigint;
        gdprBasis: string;
        userIdentifier: string;
        blockNumber: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDeletion"
  ): TypedContractMethod<
    [deletionId: BigNumberish],
    [DeletionProver.DeletionRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVaultDeletions"
  ): TypedContractMethod<[vaultId: BytesLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isDeleted"
  ): TypedContractMethod<[contentHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proveDeletion"
  ): TypedContractMethod<
    [
      vaultId: BytesLike,
      deletedContentHashes: BytesLike[],
      gdprBasis: string,
      userIdentifier: string,
      operatorSig: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerVaultOperator"
  ): TypedContractMethod<
    [vaultId: BytesLike, operator: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vaultDeletions"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "vaultOperators"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getEvent(
    key: "DeletionProved"
  ): TypedContractEvent<
    DeletionProvedEvent.InputTuple,
    DeletionProvedEvent.OutputTuple,
    DeletionProvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "VaultOperatorRegistered"
  ): TypedContractEvent<
    VaultOperatorRegisteredEvent.InputTuple,
    VaultOperatorRegisteredEvent.OutputTuple,
    VaultOperatorRegisteredEvent.OutputObject
  >;

  filters: {
    "DeletionProved(uint256,bytes32,bytes32,address,uint256,string)": TypedContractEvent<
      DeletionProvedEvent.InputTuple,
      DeletionProvedEvent.OutputTuple,
      DeletionProvedEvent.OutputObject
    >;
    DeletionProved: TypedContractEvent<
      DeletionProvedEvent.InputTuple,
      DeletionProvedEvent.OutputTuple,
      DeletionProvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "VaultOperatorRegistered(bytes32,address)": TypedContractEvent<
      VaultOperatorRegisteredEvent.InputTuple,
      VaultOperatorRegisteredEvent.OutputTuple,
      VaultOperatorRegisteredEvent.OutputObject
    >;
    VaultOperatorRegistered: TypedContractEvent<
      VaultOperatorRegisteredEvent.InputTuple,
      VaultOperatorRegisteredEvent.OutputTuple,
      VaultOperatorRegisteredEvent.OutputObject
    >;
  };
}
