/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace MemoryMarket {
  export type PackStruct = {
    packId: BigNumberish;
    contentHash: BytesLike;
    provenanceHash: BytesLike;
    seller: AddressLike;
    priceUsdc: BigNumberish;
    interactionCount: BigNumberish;
    domainTag: string;
    title: string;
    metadataUri: string;
    listed: boolean;
    delisted: boolean;
    listedAt: BigNumberish;
    purchaseCount: BigNumberish;
  };

  export type PackStructOutput = [
    packId: bigint,
    contentHash: string,
    provenanceHash: string,
    seller: string,
    priceUsdc: bigint,
    interactionCount: bigint,
    domainTag: string,
    title: string,
    metadataUri: string,
    listed: boolean,
    delisted: boolean,
    listedAt: bigint,
    purchaseCount: bigint
  ] & {
    packId: bigint;
    contentHash: string;
    provenanceHash: string;
    seller: string;
    priceUsdc: bigint;
    interactionCount: bigint;
    domainTag: string;
    title: string;
    metadataUri: string;
    listed: boolean;
    delisted: boolean;
    listedAt: bigint;
    purchaseCount: bigint;
  };

  export type PurchaseStruct = {
    purchaseId: BigNumberish;
    packId: BigNumberish;
    buyer: AddressLike;
    pricePaid: BigNumberish;
    purchasedAt: BigNumberish;
    ingestTxRef: BytesLike;
  };

  export type PurchaseStructOutput = [
    purchaseId: bigint,
    packId: bigint,
    buyer: string,
    pricePaid: bigint,
    purchasedAt: bigint,
    ingestTxRef: string
  ] & {
    purchaseId: bigint;
    packId: bigint;
    buyer: string;
    pricePaid: bigint;
    purchasedAt: bigint;
    ingestTxRef: string;
  };
}

export interface MemoryMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "PLATFORM_SHARE_BPS"
      | "SELLER_SHARE_BPS"
      | "TIMELOCK_DELAY"
      | "buyerPurchases"
      | "cancelTreasuryChange"
      | "delistPack"
      | "executeTreasuryChange"
      | "getBuyerPurchases"
      | "getPack"
      | "getPurchase"
      | "getSellerPacks"
      | "hasPurchased"
      | "listPack"
      | "owner"
      | "packCounter"
      | "packs"
      | "pendingTreasury"
      | "pendingWithdrawals"
      | "platformRevenue"
      | "platformTreasury"
      | "proposeTreasuryChange"
      | "purchaseCounter"
      | "purchasePack"
      | "purchases"
      | "renounceOwnership"
      | "sellerPacks"
      | "transferOwnership"
      | "treasuryChangeEta"
      | "usdc"
      | "withdrawPlatformRevenue"
      | "withdrawRevenue"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PackDelisted"
      | "PackListed"
      | "PackPurchased"
      | "PlatformRevenueWithdrawn"
      | "RevenueWithdrawn"
      | "TreasuryChangeCancelled"
      | "TreasuryChangeProposed"
      | "TreasuryChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_SHARE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SELLER_SHARE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIMELOCK_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyerPurchases",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTreasuryChange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "delistPack",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTreasuryChange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyerPurchases",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPack",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPurchase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellerPacks",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPurchased",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listPack",
    values: [
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "packCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "packs", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "pendingTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingWithdrawals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "platformRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposeTreasuryChange",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchasePack",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchases",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellerPacks",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryChangeEta",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRevenue",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_SHARE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SELLER_SHARE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIMELOCK_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyerPurchases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelTreasuryChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "delistPack", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeTreasuryChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyerPurchases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPack", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPurchase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellerPacks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPurchased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listPack", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "packCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "packs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeTreasuryChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchasePack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "purchases", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellerPacks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryChangeEta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRevenue",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PackDelistedEvent {
  export type InputTuple = [packId: BigNumberish, seller: AddressLike];
  export type OutputTuple = [packId: bigint, seller: string];
  export interface OutputObject {
    packId: bigint;
    seller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PackListedEvent {
  export type InputTuple = [
    packId: BigNumberish,
    seller: AddressLike,
    contentHash: BytesLike,
    priceUsdc: BigNumberish,
    domainTag: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    packId: bigint,
    seller: string,
    contentHash: string,
    priceUsdc: bigint,
    domainTag: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    packId: bigint;
    seller: string;
    contentHash: string;
    priceUsdc: bigint;
    domainTag: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PackPurchasedEvent {
  export type InputTuple = [
    purchaseId: BigNumberish,
    packId: BigNumberish,
    buyer: AddressLike,
    priceUsdc: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    purchaseId: bigint,
    packId: bigint,
    buyer: string,
    priceUsdc: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    purchaseId: bigint;
    packId: bigint;
    buyer: string;
    priceUsdc: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformRevenueWithdrawnEvent {
  export type InputTuple = [treasury: AddressLike, amount: BigNumberish];
  export type OutputTuple = [treasury: string, amount: bigint];
  export interface OutputObject {
    treasury: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevenueWithdrawnEvent {
  export type InputTuple = [seller: AddressLike, amount: BigNumberish];
  export type OutputTuple = [seller: string, amount: bigint];
  export interface OutputObject {
    seller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryChangeCancelledEvent {
  export type InputTuple = [cancelledTreasury: AddressLike];
  export type OutputTuple = [cancelledTreasury: string];
  export interface OutputObject {
    cancelledTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryChangeProposedEvent {
  export type InputTuple = [newTreasury: AddressLike, eta: BigNumberish];
  export type OutputTuple = [newTreasury: string, eta: bigint];
  export interface OutputObject {
    newTreasury: string;
    eta: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryChangedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MemoryMarket extends BaseContract {
  connect(runner?: ContractRunner | null): MemoryMarket;
  waitForDeployment(): Promise<this>;

  interface: MemoryMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_SHARE_BPS: TypedContractMethod<[], [bigint], "view">;

  SELLER_SHARE_BPS: TypedContractMethod<[], [bigint], "view">;

  TIMELOCK_DELAY: TypedContractMethod<[], [bigint], "view">;

  buyerPurchases: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  cancelTreasuryChange: TypedContractMethod<[], [void], "nonpayable">;

  delistPack: TypedContractMethod<[packId: BigNumberish], [void], "nonpayable">;

  executeTreasuryChange: TypedContractMethod<[], [void], "nonpayable">;

  getBuyerPurchases: TypedContractMethod<
    [buyer: AddressLike],
    [bigint[]],
    "view"
  >;

  getPack: TypedContractMethod<
    [packId: BigNumberish],
    [MemoryMarket.PackStructOutput],
    "view"
  >;

  getPurchase: TypedContractMethod<
    [purchaseId: BigNumberish],
    [MemoryMarket.PurchaseStructOutput],
    "view"
  >;

  getSellerPacks: TypedContractMethod<
    [seller: AddressLike],
    [bigint[]],
    "view"
  >;

  hasPurchased: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  listPack: TypedContractMethod<
    [
      contentHash: BytesLike,
      provenanceHash: BytesLike,
      priceUsdc: BigNumberish,
      interactionCount: BigNumberish,
      domainTag: string,
      title: string,
      metadataUri: string
    ],
    [bigint],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  packCounter: TypedContractMethod<[], [bigint], "view">;

  packs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        string,
        boolean,
        boolean,
        bigint,
        bigint
      ] & {
        packId: bigint;
        contentHash: string;
        provenanceHash: string;
        seller: string;
        priceUsdc: bigint;
        interactionCount: bigint;
        domainTag: string;
        title: string;
        metadataUri: string;
        listed: boolean;
        delisted: boolean;
        listedAt: bigint;
        purchaseCount: bigint;
      }
    ],
    "view"
  >;

  pendingTreasury: TypedContractMethod<[], [string], "view">;

  pendingWithdrawals: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  platformRevenue: TypedContractMethod<[], [bigint], "view">;

  platformTreasury: TypedContractMethod<[], [string], "view">;

  proposeTreasuryChange: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  purchaseCounter: TypedContractMethod<[], [bigint], "view">;

  purchasePack: TypedContractMethod<
    [packId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  purchases: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, bigint, string] & {
        purchaseId: bigint;
        packId: bigint;
        buyer: string;
        pricePaid: bigint;
        purchasedAt: bigint;
        ingestTxRef: string;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sellerPacks: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasuryChangeEta: TypedContractMethod<[], [bigint], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  withdrawPlatformRevenue: TypedContractMethod<[], [void], "nonpayable">;

  withdrawRevenue: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_SHARE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SELLER_SHARE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIMELOCK_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyerPurchases"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelTreasuryChange"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "delistPack"
  ): TypedContractMethod<[packId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeTreasuryChange"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBuyerPurchases"
  ): TypedContractMethod<[buyer: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPack"
  ): TypedContractMethod<
    [packId: BigNumberish],
    [MemoryMarket.PackStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPurchase"
  ): TypedContractMethod<
    [purchaseId: BigNumberish],
    [MemoryMarket.PurchaseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSellerPacks"
  ): TypedContractMethod<[seller: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hasPurchased"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "listPack"
  ): TypedContractMethod<
    [
      contentHash: BytesLike,
      provenanceHash: BytesLike,
      priceUsdc: BigNumberish,
      interactionCount: BigNumberish,
      domainTag: string,
      title: string,
      metadataUri: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "packCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "packs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        string,
        boolean,
        boolean,
        bigint,
        bigint
      ] & {
        packId: bigint;
        contentHash: string;
        provenanceHash: string;
        seller: string;
        priceUsdc: bigint;
        interactionCount: bigint;
        domainTag: string;
        title: string;
        metadataUri: string;
        listed: boolean;
        delisted: boolean;
        listedAt: bigint;
        purchaseCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingWithdrawals"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformRevenue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposeTreasuryChange"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "purchaseCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "purchasePack"
  ): TypedContractMethod<[packId: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "purchases"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, bigint, string] & {
        purchaseId: bigint;
        packId: bigint;
        buyer: string;
        pricePaid: bigint;
        purchasedAt: bigint;
        ingestTxRef: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sellerPacks"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasuryChangeEta"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawPlatformRevenue"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawRevenue"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PackDelisted"
  ): TypedContractEvent<
    PackDelistedEvent.InputTuple,
    PackDelistedEvent.OutputTuple,
    PackDelistedEvent.OutputObject
  >;
  getEvent(
    key: "PackListed"
  ): TypedContractEvent<
    PackListedEvent.InputTuple,
    PackListedEvent.OutputTuple,
    PackListedEvent.OutputObject
  >;
  getEvent(
    key: "PackPurchased"
  ): TypedContractEvent<
    PackPurchasedEvent.InputTuple,
    PackPurchasedEvent.OutputTuple,
    PackPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformRevenueWithdrawn"
  ): TypedContractEvent<
    PlatformRevenueWithdrawnEvent.InputTuple,
    PlatformRevenueWithdrawnEvent.OutputTuple,
    PlatformRevenueWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "RevenueWithdrawn"
  ): TypedContractEvent<
    RevenueWithdrawnEvent.InputTuple,
    RevenueWithdrawnEvent.OutputTuple,
    RevenueWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryChangeCancelled"
  ): TypedContractEvent<
    TreasuryChangeCancelledEvent.InputTuple,
    TreasuryChangeCancelledEvent.OutputTuple,
    TreasuryChangeCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryChangeProposed"
  ): TypedContractEvent<
    TreasuryChangeProposedEvent.InputTuple,
    TreasuryChangeProposedEvent.OutputTuple,
    TreasuryChangeProposedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryChanged"
  ): TypedContractEvent<
    TreasuryChangedEvent.InputTuple,
    TreasuryChangedEvent.OutputTuple,
    TreasuryChangedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PackDelisted(uint256,address)": TypedContractEvent<
      PackDelistedEvent.InputTuple,
      PackDelistedEvent.OutputTuple,
      PackDelistedEvent.OutputObject
    >;
    PackDelisted: TypedContractEvent<
      PackDelistedEvent.InputTuple,
      PackDelistedEvent.OutputTuple,
      PackDelistedEvent.OutputObject
    >;

    "PackListed(uint256,address,bytes32,uint256,string,uint256)": TypedContractEvent<
      PackListedEvent.InputTuple,
      PackListedEvent.OutputTuple,
      PackListedEvent.OutputObject
    >;
    PackListed: TypedContractEvent<
      PackListedEvent.InputTuple,
      PackListedEvent.OutputTuple,
      PackListedEvent.OutputObject
    >;

    "PackPurchased(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      PackPurchasedEvent.InputTuple,
      PackPurchasedEvent.OutputTuple,
      PackPurchasedEvent.OutputObject
    >;
    PackPurchased: TypedContractEvent<
      PackPurchasedEvent.InputTuple,
      PackPurchasedEvent.OutputTuple,
      PackPurchasedEvent.OutputObject
    >;

    "PlatformRevenueWithdrawn(address,uint256)": TypedContractEvent<
      PlatformRevenueWithdrawnEvent.InputTuple,
      PlatformRevenueWithdrawnEvent.OutputTuple,
      PlatformRevenueWithdrawnEvent.OutputObject
    >;
    PlatformRevenueWithdrawn: TypedContractEvent<
      PlatformRevenueWithdrawnEvent.InputTuple,
      PlatformRevenueWithdrawnEvent.OutputTuple,
      PlatformRevenueWithdrawnEvent.OutputObject
    >;

    "RevenueWithdrawn(address,uint256)": TypedContractEvent<
      RevenueWithdrawnEvent.InputTuple,
      RevenueWithdrawnEvent.OutputTuple,
      RevenueWithdrawnEvent.OutputObject
    >;
    RevenueWithdrawn: TypedContractEvent<
      RevenueWithdrawnEvent.InputTuple,
      RevenueWithdrawnEvent.OutputTuple,
      RevenueWithdrawnEvent.OutputObject
    >;

    "TreasuryChangeCancelled(address)": TypedContractEvent<
      TreasuryChangeCancelledEvent.InputTuple,
      TreasuryChangeCancelledEvent.OutputTuple,
      TreasuryChangeCancelledEvent.OutputObject
    >;
    TreasuryChangeCancelled: TypedContractEvent<
      TreasuryChangeCancelledEvent.InputTuple,
      TreasuryChangeCancelledEvent.OutputTuple,
      TreasuryChangeCancelledEvent.OutputObject
    >;

    "TreasuryChangeProposed(address,uint256)": TypedContractEvent<
      TreasuryChangeProposedEvent.InputTuple,
      TreasuryChangeProposedEvent.OutputTuple,
      TreasuryChangeProposedEvent.OutputObject
    >;
    TreasuryChangeProposed: TypedContractEvent<
      TreasuryChangeProposedEvent.InputTuple,
      TreasuryChangeProposedEvent.OutputTuple,
      TreasuryChangeProposedEvent.OutputObject
    >;

    "TreasuryChanged(address,address)": TypedContractEvent<
      TreasuryChangedEvent.InputTuple,
      TreasuryChangedEvent.OutputTuple,
      TreasuryChangedEvent.OutputObject
    >;
    TreasuryChanged: TypedContractEvent<
      TreasuryChangedEvent.InputTuple,
      TreasuryChangedEvent.OutputTuple,
      TreasuryChangedEvent.OutputObject
    >;
  };
}
