/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AttestationAggregator__factory } from "./AttestationAggregator__factory";
export { VaultRegistry__factory } from "./VaultRegistry__factory";
