/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AttestationAggregator {
  export type AttestationRecordStruct = {
    vaultId: BytesLike;
    contentHash: BytesLike;
    stateHash: BytesLike;
    operationType: BigNumberish;
    timestamp: BigNumberish;
    batchId: BigNumberish;
    blockNumber: BigNumberish;
  };

  export type AttestationRecordStructOutput = [
    vaultId: string,
    contentHash: string,
    stateHash: string,
    operationType: bigint,
    timestamp: bigint,
    batchId: bigint,
    blockNumber: bigint
  ] & {
    vaultId: string;
    contentHash: string;
    stateHash: string;
    operationType: bigint;
    timestamp: bigint;
    batchId: bigint;
    blockNumber: bigint;
  };
}

export interface AttestationAggregatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_BATCH_SIZE"
      | "authorisedSubmitters"
      | "batchAttest"
      | "batchCounter"
      | "contentHashToBatch"
      | "getVaultAttestationCount"
      | "getVaultAttestations"
      | "owner"
      | "renounceOwnership"
      | "setSubmitterAuthorisation"
      | "transferOwnership"
      | "verify"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchAttested"
      | "OwnershipTransferred"
      | "SubmitterAuthorised"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_BATCH_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorisedSubmitters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchAttest",
    values: [
      BytesLike[],
      BytesLike[],
      BytesLike[],
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contentHashToBatch",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultAttestationCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultAttestations",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSubmitterAuthorisation",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_BATCH_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorisedSubmitters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchAttest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contentHashToBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultAttestationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultAttestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSubmitterAuthorisation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace BatchAttestedEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    attestationCount: BigNumberish,
    submitter: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: bigint,
    attestationCount: bigint,
    submitter: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    batchId: bigint;
    attestationCount: bigint;
    submitter: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmitterAuthorisedEvent {
  export type InputTuple = [submitter: AddressLike, authorised: boolean];
  export type OutputTuple = [submitter: string, authorised: boolean];
  export interface OutputObject {
    submitter: string;
    authorised: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AttestationAggregator extends BaseContract {
  connect(runner?: ContractRunner | null): AttestationAggregator;
  waitForDeployment(): Promise<this>;

  interface: AttestationAggregatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_BATCH_SIZE: TypedContractMethod<[], [bigint], "view">;

  authorisedSubmitters: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  batchAttest: TypedContractMethod<
    [
      vaultIds: BytesLike[],
      contentHashes: BytesLike[],
      stateHashes: BytesLike[],
      operationTypes: BigNumberish[],
      timestamps: BigNumberish[]
    ],
    [bigint],
    "nonpayable"
  >;

  batchCounter: TypedContractMethod<[], [bigint], "view">;

  contentHashToBatch: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getVaultAttestationCount: TypedContractMethod<
    [vaultId: BytesLike],
    [bigint],
    "view"
  >;

  getVaultAttestations: TypedContractMethod<
    [vaultId: BytesLike, offset: BigNumberish, limit: BigNumberish],
    [
      [AttestationAggregator.AttestationRecordStructOutput[], bigint] & {
        records: AttestationAggregator.AttestationRecordStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setSubmitterAuthorisation: TypedContractMethod<
    [submitter: AddressLike, authorised: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verify: TypedContractMethod<
    [vaultId: BytesLike, contentHash: BytesLike],
    [[boolean, bigint] & { exists: boolean; blockNumber: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_BATCH_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "authorisedSubmitters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "batchAttest"
  ): TypedContractMethod<
    [
      vaultIds: BytesLike[],
      contentHashes: BytesLike[],
      stateHashes: BytesLike[],
      operationTypes: BigNumberish[],
      timestamps: BigNumberish[]
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "contentHashToBatch"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVaultAttestationCount"
  ): TypedContractMethod<[vaultId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVaultAttestations"
  ): TypedContractMethod<
    [vaultId: BytesLike, offset: BigNumberish, limit: BigNumberish],
    [
      [AttestationAggregator.AttestationRecordStructOutput[], bigint] & {
        records: AttestationAggregator.AttestationRecordStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSubmitterAuthorisation"
  ): TypedContractMethod<
    [submitter: AddressLike, authorised: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [vaultId: BytesLike, contentHash: BytesLike],
    [[boolean, bigint] & { exists: boolean; blockNumber: bigint }],
    "view"
  >;

  getEvent(
    key: "BatchAttested"
  ): TypedContractEvent<
    BatchAttestedEvent.InputTuple,
    BatchAttestedEvent.OutputTuple,
    BatchAttestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SubmitterAuthorised"
  ): TypedContractEvent<
    SubmitterAuthorisedEvent.InputTuple,
    SubmitterAuthorisedEvent.OutputTuple,
    SubmitterAuthorisedEvent.OutputObject
  >;

  filters: {
    "BatchAttested(uint256,uint256,address,uint256)": TypedContractEvent<
      BatchAttestedEvent.InputTuple,
      BatchAttestedEvent.OutputTuple,
      BatchAttestedEvent.OutputObject
    >;
    BatchAttested: TypedContractEvent<
      BatchAttestedEvent.InputTuple,
      BatchAttestedEvent.OutputTuple,
      BatchAttestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SubmitterAuthorised(address,bool)": TypedContractEvent<
      SubmitterAuthorisedEvent.InputTuple,
      SubmitterAuthorisedEvent.OutputTuple,
      SubmitterAuthorisedEvent.OutputObject
    >;
    SubmitterAuthorised: TypedContractEvent<
      SubmitterAuthorisedEvent.InputTuple,
      SubmitterAuthorisedEvent.OutputTuple,
      SubmitterAuthorisedEvent.OutputObject
    >;
  };
}
