/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AttestationAggregator } from "./AttestationAggregator";
export type { VaultRegistry } from "./VaultRegistry";
