/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace VaultRegistry {
  export type VaultStruct = {
    did: string;
    operator: AddressLike;
    createdAt: BigNumberish;
    destroyedAt: BigNumberish;
    serviceEndpoint: string;
    exists: boolean;
  };

  export type VaultStructOutput = [
    did: string,
    operator: string,
    createdAt: bigint,
    destroyedAt: bigint,
    serviceEndpoint: string,
    exists: boolean
  ] & {
    did: string;
    operator: string;
    createdAt: bigint;
    destroyedAt: bigint;
    serviceEndpoint: string;
    exists: boolean;
  };
}

export interface VaultRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "destroyVault"
      | "didToVaultId"
      | "getOperatorVaults"
      | "getVault"
      | "isActiveVault"
      | "operatorVaults"
      | "owner"
      | "registerVault"
      | "renounceOwnership"
      | "resolveDID"
      | "totalVaults"
      | "transferOwnership(bytes32,address,bytes)"
      | "transferOwnership(address)"
      | "updateServiceEndpoint"
      | "vaults"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ServiceEndpointUpdated"
      | "VaultDestroyed"
      | "VaultOwnershipTransferred"
      | "VaultRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "destroyVault",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "didToVaultId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOperatorVaults",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getVault", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "isActiveVault",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "operatorVaults",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerVault",
    values: [string, AddressLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "resolveDID", values: [string]): string;
  encodeFunctionData(
    functionFragment: "totalVaults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership(bytes32,address,bytes)",
    values: [BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateServiceEndpoint",
    values: [BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "vaults", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "destroyVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "didToVaultId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOperatorVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isActiveVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "operatorVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolveDID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership(bytes32,address,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateServiceEndpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceEndpointUpdatedEvent {
  export type InputTuple = [vaultId: BytesLike, newEndpoint: string];
  export type OutputTuple = [vaultId: string, newEndpoint: string];
  export interface OutputObject {
    vaultId: string;
    newEndpoint: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultDestroyedEvent {
  export type InputTuple = [
    vaultId: BytesLike,
    operator: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: string,
    operator: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    vaultId: string;
    operator: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultOwnershipTransferredEvent {
  export type InputTuple = [
    vaultId: BytesLike,
    previousOperator: AddressLike,
    newOperator: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: string,
    previousOperator: string,
    newOperator: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    vaultId: string;
    previousOperator: string;
    newOperator: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultRegisteredEvent {
  export type InputTuple = [
    vaultId: BytesLike,
    did: string,
    operator: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: string,
    did: string,
    operator: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    vaultId: string;
    did: string;
    operator: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VaultRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): VaultRegistry;
  waitForDeployment(): Promise<this>;

  interface: VaultRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  destroyVault: TypedContractMethod<
    [vaultId: BytesLike, operatorSignature: BytesLike],
    [void],
    "nonpayable"
  >;

  didToVaultId: TypedContractMethod<[arg0: string], [string], "view">;

  getOperatorVaults: TypedContractMethod<
    [operator: AddressLike],
    [string[]],
    "view"
  >;

  getVault: TypedContractMethod<
    [vaultId: BytesLike],
    [VaultRegistry.VaultStructOutput],
    "view"
  >;

  isActiveVault: TypedContractMethod<[vaultId: BytesLike], [boolean], "view">;

  operatorVaults: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerVault: TypedContractMethod<
    [
      did: string,
      operator: AddressLike,
      serviceEndpoint: string,
      signature: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveDID: TypedContractMethod<[did: string], [string], "view">;

  totalVaults: TypedContractMethod<[], [bigint], "view">;

  "transferOwnership(bytes32,address,bytes)": TypedContractMethod<
    [
      vaultId: BytesLike,
      newOperator: AddressLike,
      currentOpSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  "transferOwnership(address)": TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateServiceEndpoint: TypedContractMethod<
    [vaultId: BytesLike, newEndpoint: string, operatorSignature: BytesLike],
    [void],
    "nonpayable"
  >;

  vaults: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string, boolean] & {
        did: string;
        operator: string;
        createdAt: bigint;
        destroyedAt: bigint;
        serviceEndpoint: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "destroyVault"
  ): TypedContractMethod<
    [vaultId: BytesLike, operatorSignature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "didToVaultId"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "getOperatorVaults"
  ): TypedContractMethod<[operator: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVault"
  ): TypedContractMethod<
    [vaultId: BytesLike],
    [VaultRegistry.VaultStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActiveVault"
  ): TypedContractMethod<[vaultId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "operatorVaults"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerVault"
  ): TypedContractMethod<
    [
      did: string,
      operator: AddressLike,
      serviceEndpoint: string,
      signature: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDID"
  ): TypedContractMethod<[did: string], [string], "view">;
  getFunction(
    nameOrSignature: "totalVaults"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership(bytes32,address,bytes)"
  ): TypedContractMethod<
    [
      vaultId: BytesLike,
      newOperator: AddressLike,
      currentOpSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership(address)"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateServiceEndpoint"
  ): TypedContractMethod<
    [vaultId: BytesLike, newEndpoint: string, operatorSignature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vaults"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string, boolean] & {
        did: string;
        operator: string;
        createdAt: bigint;
        destroyedAt: bigint;
        serviceEndpoint: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ServiceEndpointUpdated"
  ): TypedContractEvent<
    ServiceEndpointUpdatedEvent.InputTuple,
    ServiceEndpointUpdatedEvent.OutputTuple,
    ServiceEndpointUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultDestroyed"
  ): TypedContractEvent<
    VaultDestroyedEvent.InputTuple,
    VaultDestroyedEvent.OutputTuple,
    VaultDestroyedEvent.OutputObject
  >;
  getEvent(
    key: "VaultOwnershipTransferred"
  ): TypedContractEvent<
    VaultOwnershipTransferredEvent.InputTuple,
    VaultOwnershipTransferredEvent.OutputTuple,
    VaultOwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "VaultRegistered"
  ): TypedContractEvent<
    VaultRegisteredEvent.InputTuple,
    VaultRegisteredEvent.OutputTuple,
    VaultRegisteredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ServiceEndpointUpdated(bytes32,string)": TypedContractEvent<
      ServiceEndpointUpdatedEvent.InputTuple,
      ServiceEndpointUpdatedEvent.OutputTuple,
      ServiceEndpointUpdatedEvent.OutputObject
    >;
    ServiceEndpointUpdated: TypedContractEvent<
      ServiceEndpointUpdatedEvent.InputTuple,
      ServiceEndpointUpdatedEvent.OutputTuple,
      ServiceEndpointUpdatedEvent.OutputObject
    >;

    "VaultDestroyed(bytes32,address,uint256)": TypedContractEvent<
      VaultDestroyedEvent.InputTuple,
      VaultDestroyedEvent.OutputTuple,
      VaultDestroyedEvent.OutputObject
    >;
    VaultDestroyed: TypedContractEvent<
      VaultDestroyedEvent.InputTuple,
      VaultDestroyedEvent.OutputTuple,
      VaultDestroyedEvent.OutputObject
    >;

    "VaultOwnershipTransferred(bytes32,address,address,uint256)": TypedContractEvent<
      VaultOwnershipTransferredEvent.InputTuple,
      VaultOwnershipTransferredEvent.OutputTuple,
      VaultOwnershipTransferredEvent.OutputObject
    >;
    VaultOwnershipTransferred: TypedContractEvent<
      VaultOwnershipTransferredEvent.InputTuple,
      VaultOwnershipTransferredEvent.OutputTuple,
      VaultOwnershipTransferredEvent.OutputObject
    >;

    "VaultRegistered(bytes32,string,address,uint256)": TypedContractEvent<
      VaultRegisteredEvent.InputTuple,
      VaultRegisteredEvent.OutputTuple,
      VaultRegisteredEvent.OutputObject
    >;
    VaultRegistered: TypedContractEvent<
      VaultRegisteredEvent.InputTuple,
      VaultRegisteredEvent.OutputTuple,
      VaultRegisteredEvent.OutputObject
    >;
  };
}
